/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrganizationIndexImport } from './routes/$organization/index'
import { Route as OrganizationProjectImport } from './routes/$organization/$project'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OrganizationIndexRoute = OrganizationIndexImport.update({
  path: '/$organization/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationProjectRoute = OrganizationProjectImport.update({
  path: '/$organization/$project',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$organization/$project': {
      preLoaderRoute: typeof OrganizationProjectImport
      parentRoute: typeof rootRoute
    }
    '/$organization/': {
      preLoaderRoute: typeof OrganizationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  OrganizationProjectRoute,
  OrganizationIndexRoute,
])

/* prettier-ignore-end */
